# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# generatorOptions:
#   disableNameSuffixHash: true

# resources:
# - ../../base/contour/package-install.yml


# components:
# - ../../env/dev/contour

# patchesJSON6902:
# - target:
#     group: packaging.carvel.dev
#     version: v1alpha1
#     kind: PackageInstall
#     name: contour
#   patch: |-
#     - op: add
#       path: /spec/values/1
#       value: {
#           "secretRef": {"name": "contour-packages-values-overrides"}
#             }
# secretGenerator:
# - name: contour-packages-values
#   namespace: flux-system
#   files:
#   - ../../base/contour/values.yml
#   type: Opaque
#   options:
#     annotations:
#       tkg.tanzu.vmware.com/tanzu-package: contour-packages
# - name: contour-packages-values-overrides
#   namespace: flux-system
#   files:
#   - values.yml
#   type: Opaque
#   options:
#     annotations:
#       tkg.tanzu.vmware.com/tanzu-package: contour-packages