---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tenant
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warroyo/app-team-1-gitops

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/flux-2
  prune: true
  sourceRef:
    kind: GitRepository
    name: tenant

---
apiVersion: v1
kind: Namespace
metadata:
  name: flux-tenant
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled