---
apiVersion: v1
kind: Namespace
metadata:
  name: group-0001

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tenant-flux-reconciler
  namespace: group-0001

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: group-0001-reconciler
  namespace: group-0001
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: metatmc-controller-role
subjects:
- kind: ServiceAccount
  name: tenant-flux-reconciler
  namespace: group-0001


---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: group-0001
  namespace: group-0001
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warroyo/group-0001-gitops

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: group-0001
  namespace: group-0001
spec:
  interval: 10m0s
  path: ./clusters/gke-2/namespaces
  prune: true
  serviceAccountName: tenant-flux-reconciler
  targetNamespace: group-0001
  sourceRef:
    kind: GitRepository
    name: group-0001
  patches:
    - patch: |-
        apiVersion: tmc.tanzufield.vmware.com/v1
        kind: TMCNamespace
        metadata:
          name: not used
        spec:
          fullName:
            clusterName: gke-2
            managementClusterName: attached
            provisionerName: attached
          spec:
            workspaceName: group-0001
                  
      target:
        kind: TMCNamespace