---
apiVersion: v1
kind: Namespace
metadata:
  name: group-0001

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: group-0001
  namespace: group-0001
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/warroyo/group-0001-gitops

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: group-0001
  namespace: group-0001
spec:
  interval: 10m0s
  path: ./clusters/gke-2/namespaces
  prune: true
  targetNamespace: group-0001
  sourceRef:
    kind: GitRepository
    name: group-0001
  patches:
    - patch: |-
        apiVersion: tmc.tanzufield.vmware.com/v1
        kind: TMCNamespace
        spec:
          fullName:
            clusterName: gke-2
            managementClusterName: attached
            provisionerName: attached
          spec:
            workspaceName: group-0001
                  
      target:
        kind: TMCNamespace
        # labelSelector: "app.kubernetes.io/part-of=my-app"