apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metacontrollers
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 5m
  url: https://github.com/warroyo/metacontrollers.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tmc-controller-crd
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: tmc-controller/v1/
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: metacontrollers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tmc-controller-install
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: tmc-controller/manifest/
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: metacontrollers