---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: clustergroup-gitops
  namespace: flux-system
spec:
  interval: 10m0s
  path: clustergroups/warroyo-flux/per-cluster
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: stack-config
        # Use this ConfigMap if it exists, but proceed if it doesn't.
        optional: true
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: infra-gitops