---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  serviceAccountName: pkg-gitops-pkgi-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.10.2+vmware.1-tkg.1