---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
  - name: infrastructure
  interval: 10m0s
  path: ./apps/clusters/gke-2
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: infra-gitops