apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: contour
  namespace: projectcontour
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  releaseName: contour
  chart:
    spec:
      sourceRef:
        kind: GitRepository
        name: helm-charts
        namespace: flux-system
  interval: 5m
  values:
    contour:
      image:
        repository: projectcontour/contour
    envoy:
      image:
        repository: projectcontour/envoy
      service:
        externalTrafficPolicy: Cluster
      terminationGracePeriodSeconds: 60
