apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: metacontrollers
  namespace: flux-system
spec:
  interval: 5m
  url: https://github.com/metacontroller/metacontroller
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: configmap-prop-crd
  namespace: flux-system
spec:
  interval: 10m0s
  path: v1/
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: metacontrollers
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: configmap-prop-install
  namespace: flux-system
spec:
  interval: 10m0s
  path: manifests/
  prune: true
  sourceRef:
    kind: GitRepository
    namespace: flux-system
    name: metacontrollers